apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: getnsnodes
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  verbs:
  - list
  - get
