apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: stage-tp9
  namespace: bob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stage-tp9
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: stage
