apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:

resources:
  - ../base

namePrefix: dev-

images:
  - name: nginx
    newtag: "1.27"

replicas:
  - name: wwwphp
    count: 1

patchesStrategicMerge:
  - ingress-patch.yml
